export const colors = {
  background: "#f8fafc",
  surface: "#ffffff",
  surfaceMuted: "#f8fafc",
  border: "#e5e7eb",
  borderStrong: "#cbd5e1",
  textPrimary: "#111827",
  textSecondary: "#374151",
  textMuted: "#6b7280",
  primary: "#2563eb",
  primaryStrong: "#1d4ed8",
  inverseText: "#ffffff",
  successSurface: "#ecfdf5",
  successBorder: "#86efac",
  successText: "#166534",
  warningSurface: "#ffedd5",
  warningBorder: "#fdba74",
  warningText: "#9a3412",
  dangerSurface: "#fef2f2",
  dangerBorder: "#fecaca",
  dangerText: "#991b1b",
  neutralSurface: "#f3f4f6",
  neutralBorder: "#d1d5db",
  neutralText: "#4b5563",
  infoSurface: "#eff6ff",
  infoBorder: "#bfdbfe",
  infoText: "#1e3a8a",
  energizedSurface: "#fef3c7",
  energizedBorder: "#f59e0b",
  energizedText: "#92400e",
  calmSurface: "#dcfce7",
  calmBorder: "#22c55e",
  calmText: "#166534",
  stressedSurface: "#fee2e2",
  stressedBorder: "#ef4444",
  stressedText: "#991b1b",
  tiredSurface: "#ede9fe",
  tiredBorder: "#8b5cf6",
  tiredText: "#5b21b6"
} as const;

export type AppColorToken = keyof typeof colors;
